spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cf4kq2gcocp2.ap-northeast-2.rds.amazonaws.com:3306/WePet
    username: admin
    password: wepet1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
jwt:
  secret:
    key:
      access: accessaccessaccessaccessaccessaccessasaccessaceaccessaccessaccessaccessaccessaccessasaccessace
      refresh: refreshrefreshrefreshrefreshrefreshefreshrefreshrefreshrefreshrefreshefreshrefreshrefreshrefreshrefresh